#!/usr/bin/env bash

source ~/.bashrc
tmux has-session -t aux 2>/dev/null
if [ $? != 0 ]; then
reload-ssh-agent
tmux new-session -s aux -n pyconsole -d
tmux send-keys -t aux:1 'ipython3' C-m

tmux new-window -n shell -t aux

tmux new-window -n htop -t aux
tmux send-keys -t aux:3 'htop' C-m

tmux new-window -n root-shell -t aux
tmux send-keys -t aux:4 'sudo -i' C-m

tmux select-window -t aux:1
fi

tmux attach -t aux
